export interface Product {
  name: string;
  price: string;
  image: string;
  category: string;
  subCategory: string;
}

export const products: Product[] = [
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/111.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/222.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/333.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/53.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/52.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/51.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/50.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/49.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/48.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/47.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/46.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/45.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/45.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/44.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/43.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/42.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/41.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/40.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/39.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/38.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/37.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/36.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/35.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/34.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Remaining-Bags/33.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/32.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/31.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/29.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/27.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/26.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/24.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/22.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/20.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Remaining-Bags/18.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Embriodery-Bags/em2.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Embriodery-Bags/em3.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 1̶5̶0̶0̶ 1200",
    image: `/images/Embriodery-Bags/em4.png`,
    subCategory: "Microsuede Embroidery bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Embriodery-Bags/mseb1.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Embriodery-Bags/mseb2.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Embriodery-Bags/mseb3.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Embriodery-Bags/mseb1.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Bags",
    price: "Rs 2̶0̶0̶0̶ 1500",
    image: `/images/Embriodery-Bags/mseb5.png`,
    subCategory: "Microsuede Embroidery shoulder bags",
    category: "Embroidery Bags",
  },
  {
    name: "Embroidery Shawls",
    price: "Rs 3000",
    image: `/images/Woollen-Shawls/1.png`,
    category: "Woollen Shawls",
    subCategory: "Woollen Shawls",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 1800",
    image: `/images/Pashmina-Sweaters/55.png`,
    subCategory: "Round Stripe",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 1800",
    image: `/images/Pashmina-Sweaters/56.png`,
    subCategory: "Round Stripe",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 1800",
    image: `/images/Pashmina-Sweaters/57.png`,
    subCategory: "Round Stripe",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 2400",
    image: `/images/Pashmina-Sweaters/58.png`,
    subCategory: "Full zip",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 2400",
    image: `/images/Pashmina-Sweaters/62.png`,
    subCategory: "Full zip",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 2400",
    image: `/images/Pashmina-Sweaters/63.png`,
    subCategory: "Full zip",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 1800",
    image: `/images/Pashmina-Sweaters/60.png`,
    subCategory: "Half zip",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Sweater",
    price: "Rs 2400",
    image: `/images/Pashmina-Sweaters/59.png`,
    subCategory: "Half zip",
    category: "Pashmina Sweaters",
  },
  {
    name: "Pashmina Mufflers",
    price: "Rs 1̶2̶0̶0̶ 600",
    image: `/images/Pashmina-Mufflers/1.png`,
    subCategory: "Pashmina Mufflers",
    category: "Pashmina Mufflers",
  },
  {
    name: "Pashmina Mufflers",
    price: "Rs 1̶2̶0̶0̶ 600",
    image: `/images/Pashmina-Mufflers/2.png`,
    subCategory: "Pashmina Mufflers",
    category: "Pashmina Mufflers",
  },
  {
    name: "Pashmina Mufflers",
    price: "Rs 1̶2̶0̶0̶ 600",
    image: `/images/Pashmina-Mufflers/4.png`,
    subCategory: "Pashmina Mufflers",
    category: "Pashmina Mufflers",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶50̶0̶ 1500",
    image: `/images/Pashmina-Poncho/7.png`,
    subCategory: "Pashmina Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶50̶0̶ 1500",
    image: `/images/Pashmina-Poncho/5.png`,
    subCategory: "Pashmina Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶50̶0̶ 1500",
    image: `/images/Pashmina-Poncho/6.png`,
    subCategory: "Pashmina Stripe Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶50̶0̶ 1500",
    image: `/images/Pashmina-Poncho/8.png`,
    subCategory: "Pashmina Stripe Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶00̶0̶ 1300",
    image: `/images/Pashmina-Poncho/1.png`,
    subCategory: "Pashmina Plain Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶00̶0̶ 1300",
    image: `/images/Pashmina-Poncho/2.png`,
    subCategory: "Pashmina Plain Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶00̶0̶ 1300",
    image: `/images/Pashmina-Poncho/3.png`,
    subCategory: "Pashmina Plain Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Poncho",
    price: "Rs 2̶00̶0̶ 1300",
    image: `/images/Pashmina-Poncho/4.png`,
    subCategory: "Pashmina Plain Poncho",
    category: "Pashmina Poncho",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 3̶0̶0̶0̶ 2500",
    image: `/images/Pashmina-Shawls/555.png`,
    subCategory: "Light delicate pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 3̶0̶0̶0̶ 2500",
    image: `/images/Pashmina-Shawls/444.png`,
    subCategory: "Light delicate pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 3̶0̶0̶0̶ 2500",
    image: `/images/Pashmina-Shawls/666.png`,
    subCategory: "Light delicate pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶4̶0̶0̶ 1000",
    image: `/images/Pashmina-Shawls/333.png`,
    subCategory: "Plain pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶4̶0̶0̶ 1000",
    image: `/images/Pashmina-Shawls/222.png`,
    subCategory: "Plain pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶6̶0̶0̶ 1300",
    image: `/images/Pashmina-Shawls/15.png`,
    subCategory: "8 ply pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶6̶0̶0̶ 1300",
    image: `/images/Pashmina-Shawls/kani1.png`,
    subCategory: "8 ply pashmina Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 6̶0̶0̶0̶ 3500",
    image: `/images/Pashmina-Shawls/kani2.png`,
    subCategory: "Kashmiri kani Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 6̶0̶0̶0̶ 3500",
    image: `/images/Pashmina-Shawls/kani3.png`,
    subCategory: "Kashmiri kani Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 7̶0̶0̶0̶ 5000",
    image: `/images/Pashmina-Shawls/kashmiri1.png`,
    subCategory: "Kashmiri embroidery Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 7̶0̶0̶0̶ 5000",
    image: `/images/Pashmina-Shawls/kashmiri2.png`,
    subCategory: "Kashmiri embroidery Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 7̶0̶0̶0̶ 5000",
    image: `/images/Pashmina-Shawls/kashmiri3.png`,
    subCategory: "Kashmiri embroidery Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 7̶0̶0̶0̶ 5000",
    image: `/images/Pashmina-Shawls/kashmiri4.png`,
    subCategory: "Kashmiri embroidery Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶6̶0̶0̶ 1200",
    image: `/images/Pashmina-Shawls/reversible1.png`,
    subCategory: "Reversible Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶6̶0̶0̶ 1200",
    image: `/images/Pashmina-Shawls/reversible2.png`,
    subCategory: "Reversible Shawls",
    category: "Pashmina Shawls",
  },
  {
    name: "Pashmina Shawls",
    price: "Rs 1̶6̶0̶0̶ 1200",
    image: `/images/Pashmina-Shawls/reversible3.png`,
    subCategory: "Reversible Shawls",
    category: "Pashmina Shawls",
  },
];
